app = "tarot-bot-secret"  # Уникальное имя (можно изменить)

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builder = "paketobuildpacks/builder:base"

[http_service]
  internal_port = 8080
  force_https = true
  
  [[http_service.checks]]
    interval = "30s"
    grace_period = "10s"
    method = "GET"
    path = "/"
    timeout = "5s"
